spring.application.name=mmorpg

# CONFIGURACIÓN DE CONEXIÓN (JDBC)
spring.datasource.url=jdbc:postgresql://localhost:5432/dbd_guild
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

# SCHEMA INITIALIZATION
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
spring.sql.init.schema-locations=classpath:schema.sql

# Hibernate settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true