version: '3.8'
services:
  postgres:
    image: postgres:15.3
    container_name: postgres-mmorpg-aislado
    environment:
      POSTGRES_USER: admin_raid
      POSTGRES_PASSWORD: superpassword123
      POSTGRES_DB: db_laboratorio
    ports:
      - "5435:5432"
    volumes:
      - volumen_aislado:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_raid"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  volumen_aislado: