spring.application.name=mmorpg

spring.datasource.url=jdbc:postgresql://localhost:5432/dbd_guild
spring.datasource.username=postgres
spring.datasource.password=Rpg123
spring.datasource.driver-class-name=org.postgresql.Driver


#para que NO use JPA
spring.jpa.hibernate.ddl-auto=none
