spring.application.name=mmorpg

# CONFIGURACIÓN DE CONEXION (JDBC)
spring.datasource.url=jdbc:postgresql://localhost:5432/dbd_guild
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Garantiza que JPA/Hibernate no intente crear tablas
spring.jpa.hibernate.ddl-auto=none


# INICIALIZACION DE BASE DE DATOS
# Lee y ejecuta automáticamente el archivo src/main/resources/schema.sql
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true
